#Все настройки, связанные с основным игровым процессом
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment blockui.config.default.boolean
	enablecitizenvoices = true
	#По умолчанию, при размещении схемы возле других зданий, уже существующие здания будут показаны как если бы они были 5 уровня, и с синим контуром вокруг. Это можно отключить, установив для него значение false. blockui.config.default.boolean
	neighborbuildingrendering = true
	#Как близко здание должно быть к другому, чтобы считаться соседним, в блоках. -1 = пересекающиеся, 0 = соприкасающиеся blockui.config.default.number
	# Default: 4
	# Range: -2 ~ 16
	neighborbuildingrange = 4
	#Как близко (в блоках) нужно находиться, чтобы видеть заказы на работу при ношении Строительных очков. blockui.config.default.number
	# Default: 50
	# Range: 1 ~ 250
	buildgogglerange = 50
	#При значении true границы колонии, отображаемые при использовании инструмента строительства, будут окрашены в цвет команды колонии. При значении false колония, в которой вы находитесь, будет белой, а любая другая колония — красной. blockui.config.default.boolean
	colonyteamborders = true
	#Должен ли отображаться специальный праздничный контент? blockui.config.default.boolean
	holidayfeatures = true
